#!/bin/bash

#Setting variables:
#
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/DpCAGE.configfile 

#No further edits necessary from here on ...
#

#mkdir ${fastqDIR}
cd ${fastqDIR}

#Trimming the reads with trimmomatic:
#
#echo "time ${SCRIPTS}/run_trimmomatic.sh"
#time ${SCRIPTS}/run_trimmomatic.sh

#Removing ribosomal RNA hits with tagdust:
#

Asex_rep1=Asex_fem_r1.fq
Asex_rep2=Asex_fem_r2.fq
Asex_rep3=Asex_fem_r3.fq

pE_rep1=pE_fem_r1.fq
pE_rep2=pE_fem_r2.fq
pE_rep3=pE_fem_r3.fq

males_rep1=males_r1.fq
males_rep2=males_r2.fq

OP1=${Asex_rep1}_trno_tagdusted
OP2=${Asex_rep2}_trno_tagdusted
OP3=${Asex_rep3}_trno_tagdusted
OP4=${pE_rep1}_trno_tagdusted
OP5=${pE_rep2}_trno_tagdusted
OP6=${pE_rep3}_trno_tagdusted
OP7=${males_rep1}_trno_tagdusted
OP8=${males_rep2}_trno_tagdusted

#${TAGDUST} -ref ${RNAfile} -dust 97 -t ${THREADS} -fe 3 -1 R:N ${Asex_rep1} -o ${OP1}
#${TAGDUST} -ref ${RNAfile} -dust 97 -t ${THREADS} -fe 3 -1 R:N ${Asex_rep2} -o ${OP2}
#${TAGDUST} -ref ${RNAfile} -dust 97 -t ${THREADS} -fe 3 -1 R:N ${Asex_rep3} -o ${OP3}
#${TAGDUST} -ref ${RNAfile} -dust 97 -t ${THREADS} -fe 3 -1 R:N ${pE_rep1} -o ${OP4}
#${TAGDUST} -ref ${RNAfile} -dust 97 -t ${THREADS} -fe 3 -1 R:N ${pE_rep2} -o ${OP5}
#${TAGDUST} -ref ${RNAfile} -dust 97 -t ${THREADS} -fe 3 -1 R:N ${pE_rep3} -o ${OP6}
#${TAGDUST} -ref ${RNAfile} -dust 97 -t ${THREADS} -fe 3 -1 R:N ${males_rep1} -o ${OP7}
#${TAGDUST} -ref ${RNAfile} -dust 97 -t ${THREADS} -fe 3 -1 R:N ${males_rep2} -o ${OP8}

cd ..

#Mapping the reads with the BWA aligner:
#
echo "time ${SCRIPTS}/run_BWA_alignment.sh"
#time ${SCRIPTS}/run_BWA_alignment.sh

#Scrubbing and removal of PCR duplicates:
#
BWAdir=${BASEDIR}/${EXPERIMENT}/BWAdir

cd ${BWAdir}

#for BAM in *_filtered.bam; do

#    echo "${SAMTOOLS} sort -n ${BAM} | ${SAMTOOLS} view -bh > $(basename $BAM _filtered.bam)_filtered_sorted.bam"
#    ${SAMTOOLS} sort -n ${BAM} | ${SAMTOOLS} view -bh > $(basename $BAM _filtered.bam)_filtered_sorted.bam                         

# ... scrubbing: we remove singlets left over by the samtools -f 2 -q 10 filter that
#      left one read of a read pair intact; we also remove read pairs in
#      which one read was mapped with more than a 4kb gap (presumed intron)
#      and reads with TLEN greater than 5000; potential introns >= 50 nt
#      detecting read pairs are saved for further analysis (but not removed
#      from the final set for TSRchitect analysis - Scrubbed-${BAM}.bam)
#

#${SCRIPTS}/scrubSAMfile.pl -p -i 50 -I 4000 -t 5000 -o $(basename $BAM _filtered.bam).sam -s $(basename $BAM _filtered.bam)_filtered_sorted.sam >& scrub.log              

#done


cd ..

#Counting TSS tags and determining TSRs with TSRchitect:
#
cd tsr
 mkdir BAMDIR
 cd BAMDIR

 for BAM in ../../BWAdir/*_filtered_sorted.bam
 do                                       
     ln -s ${BAM} ./                                                       # was previosly ln -s ../../${BAM} ./  
  done

     ln -s ${BASEDIR}/${GENOME_DIR}/${GENOME_GFF} PA42.4.0.gff
     cd ..
echo "... now running Rscript ${EXPERIMENT}wf*.Rscript"
 time ./xrunSwf all



